### PR TITLE
don't use os_activity_scope to avoid crashes when using multiple threads

### PR DESCRIPTION
**Pull request by sbag13**
Using tracing-oslog from multiple threads causes an app to crash randomly, because of unprotected access to `os_activity_scope_state_s`.

The implementation in this PR avoids using `on_enter` and `on_exit` for activity control, and applies a log to some activity in `on_event` directly.

### CODE REVIEW

**Comment by Absolucy** [comment]
Does this result in the complete loss of scopes?

**Comment by sbag13** [comment]
> Does this result in the complete loss of scopes?

I'm guessing you meant activities. The behavior shouldn't change, though. As you can read [here](https://developer.apple.com/documentation/os/logging/collecting_log_messages_in_activities) scope variables are passed to `os_activity_scope_enter` and `os_activity_scope_leave` to save and restore current activity state. So this is understandable that when many threads are launched they race to that variable. The problem was that `os_activity_scope_state_s` was shared between threads. Another possible solution could be creating this state variable for each thread individually.

Anyway, the same behavior can be achieved by using  [os_activity_apply](https://developer.apple.com/documentation/os/1772461-os_activity_apply) where you pass explicitly which activity should logs be placed in. Since the activity reference is stored in event's parent (span) there is no need to use `on_enter` and `on_exit` to activate activities, it can be passed in `on_event` directly to `os_activity_apply`.

**Comment by sbag13** [comment]
> Does this result in the complete loss of scopes?

It does not. Activities works as they should. Now they are activated in `on_event` method which creates local scope and immediately deactivated after event is logged. My first implementation didn't use scopes at all, cause I tried to use `os_activity_apply` which is difficult because of the FFI problems. Anyway, now scopes are used again with the difference that they are created each time event is logged instead of having one global scope (what caused threads to race).

An alternative approach could be using scope for each thread but It could cause events being logged within wrong activity in case of using async tasks.

**Comment by thomaseizinger** [comment]
Any update on this? We currently depend on this fork and it would be great to have this upstreamed. Thank you! :)

**Comment by Absolucy** [comment]
I completely forgot about this. This uh, still works, right?

**Comment by thomaseizinger** [comment]
> I completely forgot about this. This uh, still works, right?

We currently depend on this fork and have not experienced any panics :)

**Pull request merged**
